//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/BallShooterInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BallShooterInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BallShooterInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BallShooterInput"",
    ""maps"": [
        {
            ""name"": ""ActionMap"",
            ""id"": ""841f1114-a8f1-43a6-87cc-3134fea146f2"",
            ""actions"": [
                {
                    ""name"": ""BallShooterMove"",
                    ""type"": ""Value"",
                    ""id"": ""4a7516e5-b2c7-49ca-928a-1749bb537e11"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BallShooterShoot"",
                    ""type"": ""Button"",
                    ""id"": ""258f7207-e095-45ed-bc8f-be59bb4a76dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""f5ef223d-86e6-46a0-aab5-48369c34101a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""7a08c04b-5da5-4589-94a5-cf5788013244"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""9799eb8e-d8ae-4334-a4ff-fc32ae825e21"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""553e1f99-c48d-42bc-bf1a-adb6fdf6242c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""5f487db0-2abc-42a9-9e14-b921a68368ca"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""c4af24ab-f7ce-4c6d-8a4e-1bfb5f7faaf9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4c1ea72a-25a9-4f6e-a9b4-5ff8dee481bf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallShooterShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ActionMap
        m_ActionMap = asset.FindActionMap("ActionMap", throwIfNotFound: true);
        m_ActionMap_BallShooterMove = m_ActionMap.FindAction("BallShooterMove", throwIfNotFound: true);
        m_ActionMap_BallShooterShoot = m_ActionMap.FindAction("BallShooterShoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActionMap
    private readonly InputActionMap m_ActionMap;
    private List<IActionMapActions> m_ActionMapActionsCallbackInterfaces = new List<IActionMapActions>();
    private readonly InputAction m_ActionMap_BallShooterMove;
    private readonly InputAction m_ActionMap_BallShooterShoot;
    public struct ActionMapActions
    {
        private @BallShooterInput m_Wrapper;
        public ActionMapActions(@BallShooterInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @BallShooterMove => m_Wrapper.m_ActionMap_BallShooterMove;
        public InputAction @BallShooterShoot => m_Wrapper.m_ActionMap_BallShooterShoot;
        public InputActionMap Get() { return m_Wrapper.m_ActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionMapActionsCallbackInterfaces.Add(instance);
            @BallShooterMove.started += instance.OnBallShooterMove;
            @BallShooterMove.performed += instance.OnBallShooterMove;
            @BallShooterMove.canceled += instance.OnBallShooterMove;
            @BallShooterShoot.started += instance.OnBallShooterShoot;
            @BallShooterShoot.performed += instance.OnBallShooterShoot;
            @BallShooterShoot.canceled += instance.OnBallShooterShoot;
        }

        private void UnregisterCallbacks(IActionMapActions instance)
        {
            @BallShooterMove.started -= instance.OnBallShooterMove;
            @BallShooterMove.performed -= instance.OnBallShooterMove;
            @BallShooterMove.canceled -= instance.OnBallShooterMove;
            @BallShooterShoot.started -= instance.OnBallShooterShoot;
            @BallShooterShoot.performed -= instance.OnBallShooterShoot;
            @BallShooterShoot.canceled -= instance.OnBallShooterShoot;
        }

        public void RemoveCallbacks(IActionMapActions instance)
        {
            if (m_Wrapper.m_ActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionMapActions @ActionMap => new ActionMapActions(this);
    public interface IActionMapActions
    {
        void OnBallShooterMove(InputAction.CallbackContext context);
        void OnBallShooterShoot(InputAction.CallbackContext context);
    }
}
